name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      
      # Add a cache step to invalidate the cache
      - name: Cache validation data
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: ${{ runner.os }}-validation-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-validation-
      
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "Integration"
